apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting
  template:
    metadata:
      labels:
        app: meeting
    spec:
      containers: 
      - name: meeting
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/meeting:$VERSION 
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4001"
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: meeting-microservices
spec:
  selector:
    app: meeting
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001