apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cpu-memory-meeting
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meeting

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120 # wait 2 min before scaling down
      policies:
      - type: Pods
        value: 1 # remove pod
        periodSeconds: 60 # remove a pod every 60 seconds
    scaleUp:
      stabilizationWindowSeconds: 0 # instantly scale up
      policies:
      - type: Pods
        value: 1 # ad a new pod
        periodSeconds: 5 # add a new pod every 5 seconds