apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers: 
      - name: login
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/login:$VERSION 
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "1337"
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
        # startupProbe:
        #   exec:
        #     command:
        #       - cat
        #       - /tmp/started
        #       - echo
        #       - "Oskar är en noob"
        #   periodSeconds: 10
        #   failureThreshold: 3
        # readinessProbe:
        #   tcpSocket:
        #     port: 1337
        #   initialDelaySeconds: 10
        #   periodSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 1337
        #   initialDelaySeconds: 10
        #   periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: login-microservices
spec:
  selector:
    app: login
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337