apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers: 
      - name: meeting
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/gui:$VERSION 
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        resources:
          requests:
            cpu: 126m
            memory: 1024Mi
          limits:
            cpu: 256m
            memory: 2048Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: gui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000