apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers: 
      - name: user
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION 
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservices
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000