name: Deploy user microservice

on: 

  push:
    branches:
      - main
    paths:
      - './user'
  
  workflow_dispatch:

jobs:
  user-microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'user'

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: '../user/package-lock.json'
      
      #testing?

      - name: Build
        run: docker build -t $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION --file Dockerfile .
      
      - name: Publish
        run: |
          echo $CONTAINER_REGISTRY_PASSWORD | docker login $CONTAINER_REGISTRY_LOGIN_SERVER --username $CONTAINER_REGISTRY_USERNAME --password-stdin
          docker push $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      
      - name: Deploy
        run: envsubst < ../user/kubernetes/deploy.yaml | kubectl apply -f -